### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by ernado-x** [ApmeM/Simple-RSS#2]
Hello, @ApmeM !

Your library is awesome! I created fork from it. But you didn't add any license. It small confused me, because I can't add license to forked project. Could you please add license to original repository? 

May be it can be MIT, or BSD? :-)

Thank you in advance!

**Comment by ApmeM** [comment]
Hi, 
I selected MIT and add it to README.md.
Is it suitable fur you?

**Comment by ApmeM** [comment]
Aha, I also found that github now allow to select license in its format.
I add this license as well.

**Comment by ernado-x** [comment]
Yes, now it possible!
Thank you very much!
